using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine.XR;
using UnityEngine;

namespace WOLAP.src
{
    internal class ArchipelagoItemManager
    {
        public static List<ArchipelagoItem> ItemList { get { return itemList; } }

        public ArchipelagoItemManager() { }

        private static List<ArchipelagoItem> itemList = new List<ArchipelagoItem>
        {
            new ArchipelagoItem("Attorney's Badge", [], true),
            new ArchipelagoItem("Bean-Iron Badge", []),
            new ArchipelagoItem("Blood-Soaked Pocket Square", []),
            new ArchipelagoItem("Bowling Shirt Nametag", [], true),
            new ArchipelagoItem("Buffalo Bandolier", []),
            new ArchipelagoItem("CGAS Badge", [], true),
            new ArchipelagoItem("Chest Full Of Medals", []),
            new ArchipelagoItem("El Vibrato Brooch", []),
            new ArchipelagoItem("Enchanted Bandolier", []),
            new ArchipelagoItem("Fine Bandolier", []),
            new ArchipelagoItem("Gilded Lily", []),
            new ArchipelagoItem("Golden Scarab Pin", []),
            new ArchipelagoItem("Gothic Cameo", []),
            new ArchipelagoItem("Greased Bandolier", []),
            new ArchipelagoItem("Halloway's Pin", []),
            new ArchipelagoItem("Lucky Marigold", []),
            new ArchipelagoItem("Medal Of Adequacy", []),
            new ArchipelagoItem("Necromancers, I Hate 'Em Button", []),
            new ArchipelagoItem("Perfumed Pocket Square", []),
            new ArchipelagoItem("Purple Brain Pin", []),
            new ArchipelagoItem("Reinforced Pocket Square", []),
            new ArchipelagoItem("Replica Sherf Badge", []),
            new ArchipelagoItem("Revolting Brooch", []),
            new ArchipelagoItem("Rifleman Insignia Pin", []),
            new ArchipelagoItem("Rusty Deputy Badge", []),
            new ArchipelagoItem("Shimmering Pocket Square", []),
            new ArchipelagoItem("Shiny Abalone Brooch", []),
            new ArchipelagoItem("Smiling Face Button", []),
            new ArchipelagoItem("Smoking Crysanthemum", []),
            new ArchipelagoItem("Stylish Pocket Square", []),
            new ArchipelagoItem("Tentacled Badge", []),
            new ArchipelagoItem("Texas Ranger Badge", []),
            new ArchipelagoItem("Weirdly Deformed Bone", []),
            new ArchipelagoItem("3 Ball", [], true),
            new ArchipelagoItem("5 Ball", [], true),
            new ArchipelagoItem("6 Ball", [], true),
            new ArchipelagoItem("Ancient Bean Can", []),
            new ArchipelagoItem("Antique Rangefinder", []),
            new ArchipelagoItem("Bean-Iron Kettle", []),
            new ArchipelagoItem("Bean-Iron Saucepan", []),
            new ArchipelagoItem("Bean-Iron Skillet", []),
            new ArchipelagoItem("Br*** Censer", []),
            new ArchipelagoItem("Breadwood Cheat Sheet", []),
            new ArchipelagoItem("Caged Canary", []),
            new ArchipelagoItem("Can Of Infinite Beans", []),
            new ArchipelagoItem("Dramatic Goblin Skull", []),
            new ArchipelagoItem("Driftwood Sculpture", []),
            new ArchipelagoItem("El Vibrato Cone", []),
            new ArchipelagoItem("Filthy Porcelain Cone", []),
            new ArchipelagoItem("Ghost Flower", []),
            new ArchipelagoItem("Glass Sphere", []),
            new ArchipelagoItem("Goblin Spyglass", []),
            new ArchipelagoItem("Goblin Trash Sack", []),
            new ArchipelagoItem("Gun Manor Pistol Token", [], true),
            new ArchipelagoItem("Gun Manor Rifle Token", [], true),
            new ArchipelagoItem("Gun Manor Shotgun Token", [], true),
            new ArchipelagoItem("Infernal Leather Bag", []),
            new ArchipelagoItem("Large Plush Bear", []),
            new ArchipelagoItem("Large Plush Cat", []),
            new ArchipelagoItem("Large Plush Owl", []),
            new ArchipelagoItem("Lucky Horseshoe", []),
            new ArchipelagoItem("Macready's Pocketwatch", [], true),
            new ArchipelagoItem("Rucker's Ranchsack", []),
            new ArchipelagoItem("Sea Skull", []),
            new ArchipelagoItem("Shiny Ball", []),
            new ArchipelagoItem("Small Plush Bear", []),
            new ArchipelagoItem("Small Plush Kitten", []),
            new ArchipelagoItem("Small Plush Owl", []),
            new ArchipelagoItem("Smoldering Leather Bag", []),
            new ArchipelagoItem("Souvenir Spoon", []),
            new ArchipelagoItem("Stove Door", []),
            new ArchipelagoItem("Strange Glass Rectangle", []),
            new ArchipelagoItem("Sweet-Smellin' Flowers", []),
            new ArchipelagoItem("The Hedge Wizard's Orb", [], true),
            new ArchipelagoItem("Thick Leather Bag", []),
            new ArchipelagoItem("Vibrating Scapula", []),
            new ArchipelagoItem("Weird Silver Idol", []),
            new ArchipelagoItem("Worry Stone", []),
            new ArchipelagoItem("Barnaby Bob's Burnished Boots", []),
            new ArchipelagoItem("Big Furry Boots", []),
            new ArchipelagoItem("Black Boots", []),
            new ArchipelagoItem("Boost Boots", []),
            new ArchipelagoItem("Brown Boots", []),
            new ArchipelagoItem("El Vibrato Boots", []),
            new ArchipelagoItem("Extra-Large Boots", []),
            new ArchipelagoItem("Flashy Boots", []),
            new ArchipelagoItem("Hide Shoes", []),
            new ArchipelagoItem("Hightailin' Boots", []),
            new ArchipelagoItem("Infernal Leather Boots", []),
            new ArchipelagoItem("Jackboots", []),
            new ArchipelagoItem("Old Spanish Sabatons", []),
            new ArchipelagoItem("Orthopedic Boots", []),
            new ArchipelagoItem("Overly-Tanned Boots", []),
            new ArchipelagoItem("Riding Boots", []),
            new ArchipelagoItem("Running Boots", []),
            new ArchipelagoItem("Silk Nun's Boots", []),
            new ArchipelagoItem("Smoldering Leather Boots", []),
            new ArchipelagoItem("Spit-Soaked Boots", []),
            new ArchipelagoItem("Thick Leather Boots", []),
            new ArchipelagoItem("Tony's Bear-Soaked Boots", []),
            new ArchipelagoItem("Tony's Enchanted Boots", []),
            new ArchipelagoItem("Tony's Inscribed Boots", []),
            new ArchipelagoItem("Tony's Meaty Boots", []),
            new ArchipelagoItem("Tony's Shiny Boots", []),
            new ArchipelagoItem("Tony's Shootin' Boots", []),
            new ArchipelagoItem("Tony's Thick-Soled Boots", []),
            new ArchipelagoItem("Tony's Tiger-Striped Boots", []),
            new ArchipelagoItem("Wet Boots", []),
            new ArchipelagoItem("Work Boots", []),
            new ArchipelagoItem("Arcane Geode Hat", []),
            new ArchipelagoItem("Barely-Enchanted Hat", []),
            new ArchipelagoItem("Battered Old Top Hat", []),
            new ArchipelagoItem("Bean-Iron Collander", []),
            new ArchipelagoItem("Bear Hat", []),
            new ArchipelagoItem("Black Hood", []),
            new ArchipelagoItem("Bowling Ball Hat", [], true),
            new ArchipelagoItem("Burning Tophat", []),
            new ArchipelagoItem("Cat Hat", []),
            new ArchipelagoItem("Colorful Hat", []),
            new ArchipelagoItem("Cowboy Chef's Hat", []),
            new ArchipelagoItem("Crackerjack Hat", []),
            new ArchipelagoItem("Crazy Electric Helmet", []),
            new ArchipelagoItem("Cultist Leader Mask", []),
            new ArchipelagoItem("Cultist Mask", []),
            new ArchipelagoItem("Dilapidated Old Wizard Hat", []),
            new ArchipelagoItem("El Vibrato Crown", []),
            new ArchipelagoItem("El Vibrato Headband", []),
            new ArchipelagoItem("El Vibrato Helmet", []),
            new ArchipelagoItem("Ellsbury's Helmet", []),
            new ArchipelagoItem("Enchanted Buffalo Skull", []),
            new ArchipelagoItem("Extra-Black Hat", []),
            new ArchipelagoItem("Fake Pope Hat", []),
            new ArchipelagoItem("Floppy Derby", []),
            new ArchipelagoItem("Four-Gallon Hat", []),
            new ArchipelagoItem("Funerary Derby", []),
            new ArchipelagoItem("Gasmask", []),
            new ArchipelagoItem("General Gob's Hat", []),
            new ArchipelagoItem("Ghost Cowboy Hat", []),
            new ArchipelagoItem("Ghost Skin Cap", []),
            new ArchipelagoItem("Goblin Tiara", []),
            new ArchipelagoItem("Gold Tooth Crown", []),
            new ArchipelagoItem("Gold Tooth Tiara", []),
            new ArchipelagoItem("Infernal Leather Hat", []),
            new ArchipelagoItem("Kurtzfit Headband", []),
            new ArchipelagoItem("Marmotskin Cap", []),
            new ArchipelagoItem("Miner's Helmet", []),
            new ArchipelagoItem("Old Cavalry Hat", []),
            new ArchipelagoItem("Old Patrol Cap", []),
            new ArchipelagoItem("Owl Hat", []),
            new ArchipelagoItem("Prototype Stetson", []),
            new ArchipelagoItem("Really Nice Cowboy Hat", []),
            new ArchipelagoItem("Rifleman's Helmet", []),
            new ArchipelagoItem("Rusty Old Viking Helmet", []),
            new ArchipelagoItem("Sloppy Chef's Hat", []),
            new ArchipelagoItem("Sloppy Cowboy Hat", []),
            new ArchipelagoItem("Sloppy Tophat", []),
            new ArchipelagoItem("Smoldering Leather Hat", []),
            new ArchipelagoItem("Spittoon Hat", []),
            new ArchipelagoItem("Strange Head Sack", []),
            new ArchipelagoItem("Stripey Hat", []),
            new ArchipelagoItem("Teeny-Tiny Hat", []),
            new ArchipelagoItem("The Necromancer's Crown", []),
            new ArchipelagoItem("Thick Leather Hat", []),
            new ArchipelagoItem("Turnip Crown", []),
            new ArchipelagoItem("Wreath Of Laurels", [], true),
            new ArchipelagoItem("Yeast-Covered Hat", []),
            new ArchipelagoItem("Bean-Stained Pants", []),
            new ArchipelagoItem("Bearskin Pants", []),
            new ArchipelagoItem("Birthing Breeches", []),
            new ArchipelagoItem("Black Denim Pants", []),
            new ArchipelagoItem("Buffaloskin Pants", []),
            new ArchipelagoItem("Cargo Chaps", []),
            new ArchipelagoItem("Cargo Jeans", []),
            new ArchipelagoItem("Chastity Pants", []),
            new ArchipelagoItem("Coffee-Stained Pants", []),
            new ArchipelagoItem("Cursed Pants", []),
            new ArchipelagoItem("Double-Silk Pantaloons", [], true),
            new ArchipelagoItem("Eight-Legged Pants", [], true),
            new ArchipelagoItem("El Vibrato Pants", []),
            new ArchipelagoItem("Entire Leather Pants", []),
            new ArchipelagoItem("Fancy Pantry Pants", [], true),
            new ArchipelagoItem("Flexible Chaps", []),
            new ArchipelagoItem("Goblin Shortpants", []),
            new ArchipelagoItem("Goblin Trousers", []),
            new ArchipelagoItem("Infernal Breeches", []),
            new ArchipelagoItem("Inflexible Chaps", []),
            new ArchipelagoItem("Kitchen Pants", []),
            new ArchipelagoItem("Kneeling Pants", []),
            new ArchipelagoItem("Kurtzfit Pants", []),
            new ArchipelagoItem("Magician's Pants", []),
            new ArchipelagoItem("Miner's Pants", []),
            new ArchipelagoItem("Old Silk Trousers", []),
            new ArchipelagoItem("Smoldering Leather Pants", []),
            new ArchipelagoItem("Somethingskin Pants", []),
            new ArchipelagoItem("Spit-Soaked Pants", []),
            new ArchipelagoItem("Thick Chaps", []),
            new ArchipelagoItem("Thick Leather Pants", []),
            new ArchipelagoItem("Thick Quilted Pants", []),
            new ArchipelagoItem("Army-Issue Sidearm", []),
            new ArchipelagoItem("Bandit Pistol", []),
            new ArchipelagoItem("Bandit Revolver", []),
            new ArchipelagoItem("Bean-Iron Shootin' Iron", []),
            new ArchipelagoItem("Befouled Pistol", []),
            new ArchipelagoItem("Cookin' Pistol", []),
            new ArchipelagoItem("Deputy Pistol", []),
            new ArchipelagoItem("Desert Gang's Sixgun", []),
            new ArchipelagoItem("El Vibrato Pistol", []),
            new ArchipelagoItem("General Gob's Pistol", []),
            new ArchipelagoItem("Ghost Pistol", []),
            new ArchipelagoItem("Goblin Pistol", []),
            new ArchipelagoItem("Intimidating Sixgun", []),
            new ArchipelagoItem("Medical Gun", []),
            new ArchipelagoItem("Mrs. Gun's Opus", [], true),
            new ArchipelagoItem("Muck-Clogged Blunderbuss", []),
            new ArchipelagoItem("New-Fangled Pistol", []),
            new ArchipelagoItem("Rancher's Pistol", []),
            new ArchipelagoItem("Red-Hot Pistol", []),
            new ArchipelagoItem("Sigiled Pistol", []),
            new ArchipelagoItem("Silver Pistol", []),
            new ArchipelagoItem("Smoking Gun", []),
            new ArchipelagoItem("The Worst Gun", [], true),
            new ArchipelagoItem("Toilet Pistol", []),
            new ArchipelagoItem("Ancient Ring", []),
            new ArchipelagoItem("Bone-Chip Ring", []),
            new ArchipelagoItem("Bowling Championship Ring", [], true),
            new ArchipelagoItem("Branding Ring", []),
            new ArchipelagoItem("Coal Ring", []),
            new ArchipelagoItem("Coccyx With A Hole In It", []),
            new ArchipelagoItem("Cool Sapphire Ring", []),
            new ArchipelagoItem("Cow-Catcher Ring", []),
            new ArchipelagoItem("Cowseye Ring", []),
            new ArchipelagoItem("Effluvious Emerald Ring", []),
            new ArchipelagoItem("El Vibrato Ring", []),
            new ArchipelagoItem("Floral Ring", []),
            new ArchipelagoItem("Ghost Ring", []),
            new ArchipelagoItem("Glowing Ring", []),
            new ArchipelagoItem("Goblin Engagement Ring", []),
            new ArchipelagoItem("Goblin Glass Ring", []),
            new ArchipelagoItem("Goblin Lead Ring", []),
            new ArchipelagoItem("Goblin Nail Ring", []),
            new ArchipelagoItem("Huge Diamond Ring", []),
            new ArchipelagoItem("Lodestone Ring", []),
            new ArchipelagoItem("Meat-Stained Ring", []),
            new ArchipelagoItem("Military School Class Ring", []),
            new ArchipelagoItem("Nasty Ring", []),
            new ArchipelagoItem("Old Engagement Ring", []),
            new ArchipelagoItem("Ring Of Gettin' Places Faster", []),
            new ArchipelagoItem("Ring Of Inconspicuousness", []),
            new ArchipelagoItem("Ring Of Moderate Unpunchability", []),
            new ArchipelagoItem("Ring Of Smart Thinkin'", []),
            new ArchipelagoItem("Ring Of Strongth", []),
            new ArchipelagoItem("Sandalwood Ring", []),
            new ArchipelagoItem("Santa Cortada's Ring", []),
            new ArchipelagoItem("Serpentine Ring", []),
            new ArchipelagoItem("Silicon Ring", []),
            new ArchipelagoItem("Special Magic Ring", []),
            new ArchipelagoItem("Thaumomoprhic Diorite Ring", []),
            new ArchipelagoItem("Unbreakable Ruby Ring", []),
            new ArchipelagoItem("Artillery Saber", []),
            new ArchipelagoItem("Balanced Billiards Cue", [], true),
            new ArchipelagoItem("Barry Knife", []),
            new ArchipelagoItem("Bean-Iron Ladle", []),
            new ArchipelagoItem("Bean-Iron Spatula", []),
            new ArchipelagoItem("Bean-Iron Whisk", []),
            new ArchipelagoItem("Blechscalibur", []),
            new ArchipelagoItem("Bloodied Cleaver", []),
            new ArchipelagoItem("Bone Sword", []),
            new ArchipelagoItem("Bowling Pin", [], true),
            new ArchipelagoItem("Brass Knuckles", []),
            new ArchipelagoItem("Broken Board", []),
            new ArchipelagoItem("Bush Whacker", [], true),
            new ArchipelagoItem("Cactus Club", []),
            new ArchipelagoItem("Clown Knife", []),
            new ArchipelagoItem("Construction Sledgehammer", []),
            new ArchipelagoItem("Crowbar", []),
            new ArchipelagoItem("El Vibrato Club", []),
            new ArchipelagoItem("Fancy Knife", []),
            new ArchipelagoItem("Fang-Gloves", []),
            new ArchipelagoItem("Goblin Trashbat", []),
            new ArchipelagoItem("Gulch Goblin Axe", []),
            new ArchipelagoItem("Gulch Goblin Spatula", []),
            new ArchipelagoItem("Hammer", []),
            new ArchipelagoItem("Hard Loaf", []),
            new ArchipelagoItem("Hedge Clippers", [], true),
            new ArchipelagoItem("Infernal Mallet", []),
            new ArchipelagoItem("Jumbo Jumbo Shrimp Fork", [], true),
            new ArchipelagoItem("Leather Shears", []),
            new ArchipelagoItem("Monkey Wrench", []),
            new ArchipelagoItem("Mushroom-Covered Bone", []),
            new ArchipelagoItem("Nailgoves", []),
            new ArchipelagoItem("Old Cavalry Saber", []),
            new ArchipelagoItem("Old Pickaxe", []),
            new ArchipelagoItem("Pickaxe", []),
            new ArchipelagoItem("Plunger", []),
            new ArchipelagoItem("Red-Hot Poker", []),
            new ArchipelagoItem("Repurposed Cult Dagger", []),
            new ArchipelagoItem("Rock Hammer", []),
            new ArchipelagoItem("Spider Axe", [], true),
            new ArchipelagoItem("St. Beefus' Thigh", []),
            new ArchipelagoItem("Stainless Steel Bean Pan", [], true),
            new ArchipelagoItem("Stuffed Gun", [], true),
            new ArchipelagoItem("Sweet Sword", []),
            new ArchipelagoItem("The Carver", [], true),
            new ArchipelagoItem("Tuna Fork", []),
            new ArchipelagoItem("Ungulith-Horn Gloves", []),
            new ArchipelagoItem("Varmint Skinnin' Knife", []),
            new ArchipelagoItem("Weird Knife", []),
            new ArchipelagoItem("Wobbly Billiards Cue", [], true),
            new ArchipelagoItem("Kellogg Grain Flakes", []),
            new ArchipelagoItem("Cheap Cigar", [], true),
            new ArchipelagoItem("Can Of Kerosene", []),
            new ArchipelagoItem("1878 Nautical Almanac", [], true),
            new ArchipelagoItem("Advanced Beancraft", []),
            new ArchipelagoItem("Advanced Cow Punchin'", []),
            new ArchipelagoItem("Basics Of Gun Law", [], true),
            new ArchipelagoItem("Beans Illustrated", []),
            new ArchipelagoItem("The Best Love Poem Ever Written", []),
            new ArchipelagoItem("Burned Leatherworking Manual", []),
            new ArchipelagoItem("Cannon Loading For Idjits", []),
            new ArchipelagoItem("Progressive Nex-Mex Skillbook", []),
            new ArchipelagoItem("Desert Eatin' And Drinkin'", []),
            new ArchipelagoItem("The Diary Of Alexandria Alexandria", []),
            new ArchipelagoItem("Duel Law", [], true),
            new ArchipelagoItem("Duelling Banjos", [], true),
            new ArchipelagoItem("Forgotten Lore", []),
            new ArchipelagoItem("Fun Law: Rules For Parlor Games", [], true),
            new ArchipelagoItem("Get Crackin': A Guide To Modern Safes", []),
            new ArchipelagoItem("Gold Medal Silversmithing", []),
            new ArchipelagoItem("Hedging Your Bets", [], true),
            new ArchipelagoItem("How To \"Cheat\" At \"Poker\"", []),
            new ArchipelagoItem("Kickin' Ass And Chewin' Gum", []),
            new ArchipelagoItem("Locks And How To Pick Them", []),
            new ArchipelagoItem("Mind Your Meat", []),
            new ArchipelagoItem("Modern Snake Oiler", []),
            new ArchipelagoItem("Mycology, Yourcology", []),
            new ArchipelagoItem("Oils I Have Known", []),
            new ArchipelagoItem("Percussive Maintenance", []),
            new ArchipelagoItem("The Quick And The Drunk", []),
            new ArchipelagoItem("Rich Vein, Poor Vein", []),
            new ArchipelagoItem("Tanning And Tanning", []),
            new ArchipelagoItem("To Serve Food To Mankind", []),
            new ArchipelagoItem("Walking Stupid", []),
            new ArchipelagoItem("1.2337\" Diameter Tin Can", [], true),
            new ArchipelagoItem("A Bunch Of Really Small Guns", []),
            new ArchipelagoItem("A Pile Of Loose Chili Beans", [], true),
            new ArchipelagoItem("A Year's Supply Of Dynamite", []),
            new ArchipelagoItem("Artillery Targeting Flare", []),
            new ArchipelagoItem("Attic-Opening Stick", [], true),
            new ArchipelagoItem("Bag Of Grease", []),
            new ArchipelagoItem("Bag Of Mixed Grain", []),
            new ArchipelagoItem("Bale Of Cowsbane", []),
            new ArchipelagoItem("Big Coil Of Barbed Wire", []),
            new ArchipelagoItem("Blank Sheet Music", [], true),
            new ArchipelagoItem("Blue Chalk", [], true),
            new ArchipelagoItem("Bottle Of Ghost Whiskey", []),
            new ArchipelagoItem("Box Of Science Doohickeys", [], true),
            new ArchipelagoItem("Breadwood Bread Bowl x5", []),
            new ArchipelagoItem("Breadwood Logging Permit Forms", []),
            new ArchipelagoItem("Breadwood Logging Report", []),
            new ArchipelagoItem("Breadwood Logging Report Folder", []),
            new ArchipelagoItem("Breadwood's Missing Mail", []),
            new ArchipelagoItem("Broken Leg Pills", []),
            new ArchipelagoItem("Buffalo Pile Locker Key", []),
            new ArchipelagoItem("Buffalo Soldier Diagram", []),
            new ArchipelagoItem("Burned Scroll", []),
            new ArchipelagoItem("Cargo Car Key", []),
            new ArchipelagoItem("Charred Locket", []),
            new ArchipelagoItem("Child's Bracelet", []),
            new ArchipelagoItem("Chili Sin Pistoles", [], true),
            new ArchipelagoItem("Chili Sin Pistoles (Muerto)", [], true),
            new ArchipelagoItem("Chili Spices", [], true),
            new ArchipelagoItem("Chuck's Key", []),
            new ArchipelagoItem("Circus Show Ticket", []),
            new ArchipelagoItem("Circus Ticket", []),
            new ArchipelagoItem("Clip-On Bow Tie", []),
            new ArchipelagoItem("Comedy Flier", []),
            new ArchipelagoItem("Creepy Whispering Stone", []),
            new ArchipelagoItem("Cryptic Note About Ley Lines", []),
            new ArchipelagoItem("Curly's Auto-Gyrotheodolite", []),
            new ArchipelagoItem("Curly's Compass", []),
            new ArchipelagoItem("Curly's Strongbox", []),
            new ArchipelagoItem("Dave's Secret Sauce Recipe", []),
            new ArchipelagoItem("Demi-Culverin Cannonball", []),
            new ArchipelagoItem("Desert Ape Skeleton", []),
            new ArchipelagoItem("Dictionary Page (Poach)", [], true),
            new ArchipelagoItem("Dining Car Key", []),
            new ArchipelagoItem("Discipline Slip", []),
            new ArchipelagoItem("El Vibrato Cross", []),
            new ArchipelagoItem("El Vibrato Cylinder", []),
            new ArchipelagoItem("El Vibrato Device", []),
            new ArchipelagoItem("El Vibrato Model Bridge", []),
            new ArchipelagoItem("El Vibrato Rod", []),
            new ArchipelagoItem("El Vibrato Transponder", []),
            new ArchipelagoItem("Elevator Button", [], true),
            new ArchipelagoItem("Emergency Form Transfer Envelope", []),
            new ArchipelagoItem("Fort Treason Ballistics Chart", []),
            new ArchipelagoItem("Forty Loaves Of Bread", []),
            new ArchipelagoItem("Gas Cap", []),
            new ArchipelagoItem("Geometry Textbook", [], true),
            new ArchipelagoItem("Ghost Pencil", []),
            new ArchipelagoItem("Ghost Staple Remover", []),
            new ArchipelagoItem("Ghost Stapler", []),
            new ArchipelagoItem("Ghostwood Visitor's ID", []),
            new ArchipelagoItem("Ghostwood Visitor's Permit", []),
            new ArchipelagoItem("Glass Eye", []),
            new ArchipelagoItem("Goblet Of Blood", []),
            new ArchipelagoItem("Gore-Splattered Scroll", []),
            new ArchipelagoItem("Green Green Apple Jellybeans", []),
            new ArchipelagoItem("Gun Manor Carriage House Key", [], true),
            new ArchipelagoItem("Gun Manor Guest Room Key", [], true),
            new ArchipelagoItem("Gun Manor Photo", [], true),
            new ArchipelagoItem("Gustavson Gulch Treasure Cave Key", []),
            new ArchipelagoItem("Gustavson Gulch Treasure Cave Key (Spare)", []),
            new ArchipelagoItem("Half A Ton Of Yeast", []),
            new ArchipelagoItem("High-Tech Drill Bit", []),
            new ArchipelagoItem("Honey Jelly Bean", []),
            new ArchipelagoItem("Interesting Rock", []),
            new ArchipelagoItem("Jumbleneck Mine Elevator Key", []),
            new ArchipelagoItem("Kellogg Ranch Keyring", []),
            new ArchipelagoItem("Kellogg Ranch Workout Regimen", []),
            new ArchipelagoItem("Kellogg's Grain Flakes Recipe", []),
            new ArchipelagoItem("Key Fragment 1", []),
            new ArchipelagoItem("Key Fragment 2", []),
            new ArchipelagoItem("Key Fragment 3", []),
            new ArchipelagoItem("Key To P.O. Box 114", []),
            new ArchipelagoItem("Key To P.O. Box 441", []),
            new ArchipelagoItem("Key-Shaped El Vibrato Device", []),
            new ArchipelagoItem("Left Half Of Curly's Map", []),
            new ArchipelagoItem("Letter To Roy Bean", []),
            new ArchipelagoItem("Lime Lime Jellybeans", []),
            new ArchipelagoItem("List Of Buffalo Bones", []),
            new ArchipelagoItem("Lucky Cap", []),
            new ArchipelagoItem("Marching Orders", []),
            new ArchipelagoItem("Mary Stearns' Diary", []),
            new ArchipelagoItem("Mint Mint Jellybeans", []),
            new ArchipelagoItem("Mrs. Gun's Blueprint", [], true),
            new ArchipelagoItem("Mule Rental Contract", []),
            new ArchipelagoItem("Mushroom Map", []),
            new ArchipelagoItem("Mushroom Plucking Pliers", []),
            new ArchipelagoItem("Nearly-Empty Herbicide Can", [], true),
            new ArchipelagoItem("Overdue Breadwood Book", []),
            new ArchipelagoItem("Owl Camera", []),
            new ArchipelagoItem("Packrat Skeleton", []),
            new ArchipelagoItem("Paper Bag", []),
            new ArchipelagoItem("Passenger Car Key", []),
            new ArchipelagoItem("Photo Of L'ardest", [], true),
            new ArchipelagoItem("Picture Of Mary Stearns", []),
            new ArchipelagoItem("Plaid Skirt", [], true),
            new ArchipelagoItem("Pope's Pelvis", []),
            new ArchipelagoItem("Postal Code Sheet", []),
            new ArchipelagoItem("Purple Grass", []),
            new ArchipelagoItem("Pvt. Lemmon's Diary", []),
            new ArchipelagoItem("Pvt. Matthau's Diary", []),
            new ArchipelagoItem("Recovered Mug", []),
            new ArchipelagoItem("Remains Of The Potemkin Gang", []),
            new ArchipelagoItem("Right Half Of Curly's Map", []),
            new ArchipelagoItem("Robe Receipt", []),
            new ArchipelagoItem("Santa Cortada's Skull", []),
            new ArchipelagoItem("Saute Knife", []),
            new ArchipelagoItem("Shaker Of Saltpeter", []),
            new ArchipelagoItem("Sharpened Ghost Pencil", []),
            new ArchipelagoItem("Shaving Cream Pie", []),
            new ArchipelagoItem("Shower Curtain", [], true),
            new ArchipelagoItem("Silver-Plated Barbed Wire", []),
            new ArchipelagoItem("Skull With An Odd Tag On It", []),
            new ArchipelagoItem("Slide Whistle", []),
            new ArchipelagoItem("Small Blowtorch", [], true),
            new ArchipelagoItem("Southeast-Western Murder Pepper", []),
            new ArchipelagoItem("Spooky Lullaby Sheet Music", [], true),
            new ArchipelagoItem("St. Beefus' Finger", []),
            new ArchipelagoItem("Sticky Note", []),
            new ArchipelagoItem("Strange Stone Arrow", []),
            new ArchipelagoItem("Syrup Tap", []),
            new ArchipelagoItem("Tannery Back Door Key", []),
            new ArchipelagoItem("Tannery St. Rage Key", []),
            new ArchipelagoItem("Tea Service", [], true),
            new ArchipelagoItem("Tiny Stick Of Dynamite", [], true),
            new ArchipelagoItem("Toy Skeletons", []),
            new ArchipelagoItem("Unstable Stick Of Dynamite", []),
            new ArchipelagoItem("Very Thick Spectacles", []),
            new ArchipelagoItem("Wad Of Stuffing", [], true),
            new ArchipelagoItem("Weird Rock Sample", []),
            new ArchipelagoItem("Whining El Vibrato Object", []),
            new ArchipelagoItem("A Portable Alchemistry Set", []),
            new ArchipelagoItem("A Portable Arcane Oven", []),
            new ArchipelagoItem("A Portable Leatherwork Bench", []),
            new ArchipelagoItem("All-Purpose Beans x2", []),
            new ArchipelagoItem("Balloon", []),
            new ArchipelagoItem("Bean-Iron Nugget", []),
            new ArchipelagoItem("Blank Postcard", []),
            new ArchipelagoItem("Bottle Of Buffalo Tranquilizers", []),
            new ArchipelagoItem("Cool Sapphire", []),
            new ArchipelagoItem("Cowseye", []),
            new ArchipelagoItem("Delicate Bean-Iron Nugget", []),
            new ArchipelagoItem("Dense Bean-Iron Nugget", []),
            new ArchipelagoItem("Disturbing Portrait", []),
            new ArchipelagoItem("Elaborate Puzzle Box", []),
            new ArchipelagoItem("Handful Of Old Coins", []),
            new ArchipelagoItem("Hanky", []),
            new ArchipelagoItem("Herbal Remedy", []),
            new ArchipelagoItem("Infernal Soul Fragment", []),
            new ArchipelagoItem("Jaw Harp", []),
            new ArchipelagoItem("Miniature Piano", []),
            new ArchipelagoItem("Personalized Gun Manor Shotglass", [], true),
            new ArchipelagoItem("Pocketknife", []),
            new ArchipelagoItem("Polished Diorite", []),
            new ArchipelagoItem("Puzzle Cube", []),
            new ArchipelagoItem("Shovel", []),
            new ArchipelagoItem("Silenter", [], true),
            new ArchipelagoItem("Strange Lamp", []),
            new ArchipelagoItem("Strange Silvery Crystal", []),
            new ArchipelagoItem("Superdense Coal", []),
            new ArchipelagoItem("Unbreakable Ruby", []),
            new ArchipelagoItem("Silver Nugget x5", []),
            new ArchipelagoItem("Handful Of Nails x4", []),
            new ArchipelagoItem("Stock Certificate x3", []),
            new ArchipelagoItem("Human Ashes x2", []),
            new ArchipelagoItem("Cheap Wine x11", []),
            new ArchipelagoItem("Sulphur Match x4", []),
            new ArchipelagoItem("Military Medical Supplies", []),
            new ArchipelagoItem("Decent Booze", []),
            new ArchipelagoItem("Cheap Booze", []),
            new ArchipelagoItem("Lead Pie", []),
            new ArchipelagoItem("Drugs", []),
            new ArchipelagoItem("Goblin Sandwich x5", []),
            new ArchipelagoItem("Goblin Chicory x3", []),
            new ArchipelagoItem("A Length Of Rope", []),
            new ArchipelagoItem("Tainted Milk x3", []),
            new ArchipelagoItem("Gold Tooth x3", []),
            new ArchipelagoItem("Potted Meat", []),
            new ArchipelagoItem("Bottle Of Laudanum x6", []),
            new ArchipelagoItem("Unrefined Meat Nugget x4", []),
            new ArchipelagoItem("Bundle Of Bones", []),
            new ArchipelagoItem("Ghost Pickle x3", []),
            new ArchipelagoItem("\"Cotton Candy\"", []),
            new ArchipelagoItem("Dynamite x5", []),
            new ArchipelagoItem("Dynamite x10", []),
            new ArchipelagoItem("Lasso x3", []),
            new ArchipelagoItem("El Vibrato Fluid x5", []),
            new ArchipelagoItem("Can Of Schmaltz Blue Ribbon x3", []),
            new ArchipelagoItem("Sack Of Meat Nuggets", []),
            new ArchipelagoItem("Perfect Cup Of Coffee", []),
            new ArchipelagoItem("El Vibrato Seltzer x3", []),
            new ArchipelagoItem("Tripe Pie", []),
            new ArchipelagoItem("Decent Whiskey x2", []),
            new ArchipelagoItem("Patent Emetic x3", []),
            new ArchipelagoItem("Skull Chips x3", []),
            new ArchipelagoItem("Handful Of Loose Teeth x3", []),
            new ArchipelagoItem("El Vibrato Punchcard (Complicated) x5", []),
            new ArchipelagoItem("El Vibrato Punchcard x5", []),
            new ArchipelagoItem("El Vibrato Scraps x8", []),
            new ArchipelagoItem("El Vibrato Scraps x45", []),
            new ArchipelagoItem("Skeleton Bone x4", []),
            new ArchipelagoItem("Needle x5", []),
            new ArchipelagoItem("Jar Of Moonshine", []),
            new ArchipelagoItem("Jar Of Peanut Butter", []),
            new ArchipelagoItem("Goat Steak", []),
            new ArchipelagoItem("Moon Bits", []),
            new ArchipelagoItem("Fancy Coffee", []),
            new ArchipelagoItem("Spider Pie", [], true),
            new ArchipelagoItem("Tinned Caviar x3", [], true),
            new ArchipelagoItem("Old-Timey Ointment x3", [], true),
            new ArchipelagoItem("Instant Grits", []),
            new ArchipelagoItem("Plum Pudding", []),
            new ArchipelagoItem("Blackened Beans", []),
            new ArchipelagoItem("Disposable Binoculars x2", []),
            new ArchipelagoItem("Army Field Trauma Kit", []),
            new ArchipelagoItem("Military-Grade Whiskey", []),
            new ArchipelagoItem("Hard Tack", []),
            new ArchipelagoItem("Gulch Goblin Lollipop", []),
            new ArchipelagoItem("Snake Liver x3", []),
            new ArchipelagoItem("Snake Venom Bladder x3", []),
            new ArchipelagoItem("Snake Spleen x3", []),
            new ArchipelagoItem("Apple", []),
            new ArchipelagoItem("Carrot", []),
            new ArchipelagoItem("Gold Skull", [], true),
            new ArchipelagoItem("Stock Certificate", [], true),
            new ArchipelagoItem("Spider Ring", [], true),
            new ArchipelagoItem("Manley's Finest Cotton Candy Schnapps", [], true),
            new ArchipelagoItem("Magic-Infused Salad", [], true),
            new ArchipelagoItem("NE North Central Logging Permit", []),
            new ArchipelagoItem("Ghost Coach To Gun Manor", [], true),
            new ArchipelagoItem("English-Goblintongue Dictionary", []),
            new ArchipelagoItem("Can Of Oil", []),
            new ArchipelagoItem("Packet Of Cowsbane Seeds", []),
            new ArchipelagoItem("Lactarius Dirtihippica mushroom x4", []),
            new ArchipelagoItem("Silver-Toothed Skull", [])
        };
    }
}
