using BepInEx;
using System;
using System.Collections.Generic;
using System.Text;

namespace WOLAP
{
    internal class CheckLocationManager
    {
        public static List<CheckLocation> LocationList { get { return locationList; } }

        public CheckLocationManager()
        {

        }

        public CheckLocation GetLocation(string locName)
        {
            if (locName.IsNullOrWhiteSpace()) return null;

            return LocationList.Find(loc => loc.Name == locName);
        }

        private static List<CheckLocation> locationList = new List<CheckLocation>
        {
            new CheckLocation("Your Family's Farm - Your Bookcase", false),
            new CheckLocation("Your Family's Farm - Souvenir Shelf (Item 1)", true),
            new CheckLocation("Your Family's Farm - Souvenir Shelf (Item 2)", true),
            new CheckLocation("Your Family's Farm - Rufus' Toybox", false),
            new CheckLocation("Your Family's Farm - Father's Gift", false),
            new CheckLocation("Your Family's Farm - Mother's Gift", false),
            new CheckLocation("Dirtwater - Spittoon", false),
            new CheckLocation("Dirtwater - Flower Girl", false),
            new CheckLocation("Dirtwater Guest Room - Table", false),
            new CheckLocation("Dirtwater Saloon - Bartender's Mini Piano", false),
            new CheckLocation("Dirtwater Saloon - Chef's Mail Key", false),
            new CheckLocation("Dirtwater Saloon - Chef's Quest Complete", false),
            new CheckLocation("Dirtwater Post Office - Postal Codes", false),
            new CheckLocation("Dirtwater Post Office - P.O. Box 114", false),
            new CheckLocation("Dirtwater Post Office - P.O. Box 441", false),
            new CheckLocation("Dirtwater Mercantile - Item 1", false),
            new CheckLocation("Dirtwater Mercantile - Item 2", false),
            new CheckLocation("Dirtwater (Tony's Boots) - Item 1", false),
            new CheckLocation("Dirtwater (Tony's Boots) - Item 2", false),
            new CheckLocation("Dirtwater (Tony's Boots) - Item 3", false),
            new CheckLocation("Dirtwater (Tony's Boots) - Bonus Item", false),
            new CheckLocation("Dirtwater (Murray's Curiosity & Bean) - Item 1", false),
            new CheckLocation("Dirtwater (Murray's Curiosity & Bean) - Item 2", false),
            new CheckLocation("Dirtwater (Murray's Curiosity & Bean) - Item 3", false),
            new CheckLocation("Dirtwater (Murray's Curiosity & Bean) - Item 4", false),
            new CheckLocation("Dirtwater (Murray's Curiosity & Bean) - Bonus Item", false),
            new CheckLocation("Dirtwater (Grady's Fine Leather Goods) - Item 1", false),
            new CheckLocation("Dirtwater (Grady's Fine Leather Goods) - Item 2", false),
            new CheckLocation("Dirtwater (Grady's Fine Leather Goods) - Item 3", false),
            new CheckLocation("Dirtwater (Grady's Fine Leather Goods) - Bonus Item", false),
            new CheckLocation("Dirtwater (Alexandria's Bookstore) - Item 1", false),
            new CheckLocation("Dirtwater (Alexandria's Bookstore) - Item 2", false),
            new CheckLocation("Dirtwater (Alexandria's Bookstore) - Item 3", false),
            new CheckLocation("Dirtwater (Alexandria's Bookstore) - Item 4", false),
            new CheckLocation("Dirtwater (Alexandria's Bookstore) - Item 5", false),
            new CheckLocation("Dirtwater (Alexandria's Bookstore) - Item 6", false),
            new CheckLocation("Dirtwater (Alexandria's Bookstore) - Item 7", false),
            new CheckLocation("Dirtwater (Alexandria's Bookstore) - Bonus Item", false),
            new CheckLocation("Desert House - Macready's Grave", true),
            new CheckLocation("Desert House - Gang Shakedown", false),
            new CheckLocation("Desert House - Gang Killed", false),
            new CheckLocation("Shaggy Dog Cave - Bean-Iron Deposit", false),
            new CheckLocation("Silversmith's House - Spittoon", false),
            new CheckLocation("Silversmith's House - Safe", false),
            new CheckLocation("Silversmith's House - Shelf (Item 1)", false),
            new CheckLocation("Silversmith's House - Shelf (Item 2)", false),
            new CheckLocation("Danny's Tannery - Toolbox (Item 1)", false),
            new CheckLocation("Danny's Tannery - Toolbox (Item 2)", false),
            new CheckLocation("Danny's Tannery - Center Fight (Item 1)", false),
            new CheckLocation("Danny's Tannery - Center Fight (Item 2)", false),
            new CheckLocation("Danny's Tannery - Center Skeleton", false),
            new CheckLocation("Stearns Ranch - Smoking Flower", false),
            new CheckLocation("Stearns Ranch - Outhouse Beast Defeated", false),
            new CheckLocation("Stearns Ranch - Jethro's Bones", false),
            new CheckLocation("Stearns Ranch House - Lockbox", false),
            new CheckLocation("Stearns Ranch House - Pot", false),
            new CheckLocation("Stearns Ranch House - Burnt Bookshelf", false),
            new CheckLocation("Stearns Ranch Cellar - Safe", false),
            new CheckLocation("Stearns Ranch Cellar - Blood Altar", false),
            new CheckLocation("Snakepit Mine - Bean-Iron Deposit", false),
            new CheckLocation("Snakepit Mine - The Pick in the Stone", false),
            new CheckLocation("The Daveyard - First Grave", false),
            new CheckLocation("The Daveyard - Dave J's Grave", false),
            new CheckLocation("The Daveyard - Far-Right Bone PIle", false),
            new CheckLocation("The Daveyard Mausoleum - Rag Pile (Item 1)", false),
            new CheckLocation("The Daveyard Mausoleum - Rag Pile (Item 2)", false),
            new CheckLocation("The Daveyard Mausoleum - Rag Pile (Item 3)", false),
            new CheckLocation("The Daveyard Mausoleum - The Skeleton of Dave B. Defeated", false),
            new CheckLocation("Buttonwillow's Store - Item 1", false),
            new CheckLocation("Buttonwillow's Store - Item 2", false),
            new CheckLocation("Buttonwillow's Store - Item 3", false),
            new CheckLocation("Buttonwillow's Store - Item 4", false),
            new CheckLocation("Buttonwillow's Store - Item 5", false),
            new CheckLocation("Buttonwillow's Store - Item 6", false),
            new CheckLocation("Buttonwillow's Store - Item 7", false),
            new CheckLocation("Cavern Canyon Spider Cave - Weapens Box", false),
            new CheckLocation("Cavern Canyon Spider Cave - Medisun Box", false),
            new CheckLocation("Cavern Canyon Spider Cave - Booze Box", false),
            new CheckLocation("Cavern Canyon - Stripey Hat Gang Killed (Item 2)", false),
            new CheckLocation("Cavern Canyon Bar - Bartender's Bones", false),
            new CheckLocation("Cavern Canyon Bar - Behind the Bar", false),
            new CheckLocation("Cavern Canyon Kitchen - Doug Rescued", false),
            new CheckLocation("Fort Cowardice Mess Hall - Table (Item 1)", false),
            new CheckLocation("Fort Cowardice Mess Hall - Table (Item 2)", false),
            new CheckLocation("Fort Cowardice Mess Hall - Spice Rack", false),
            new CheckLocation("Fort Cowardice Back Office - General Gob's Hat", false),
            new CheckLocation("Fort Cowardice Back Office - General Gob's Pistol", false),
            new CheckLocation("Fort Cowardice Back Office - Pie Safe", false),
            new CheckLocation("Fort Cowardice First Tent - Back-Left Footlocker", false),
            new CheckLocation("Fort Cowardice First Tent - Front-Right Footlocker", false),
            new CheckLocation("Fort Cowardice First Tent - Back-Right Footlocker", false),
            new CheckLocation("Fort Cowardice Math Tent - Desk Papers", false),
            new CheckLocation("Fort Cowardice Math Tent - Shelves", false),
            new CheckLocation("Fort Cowardice Math Tent - Safe", false),
            new CheckLocation("Fort Cowardice Goblin Caves - First Spyglass Drop", false),
            new CheckLocation("Gustavson Gulch - Deli Hut", false),
            new CheckLocation("Gustavson Gulch Storage Hut - Random Item", false),
            new CheckLocation("Gustavson Gulch Storage Hut - More Random Item", false),
            new CheckLocation("Gustavson Gulch Storage Hut - Even Randomer Item", false),
            new CheckLocation("Gustavson Gulch Storage Hut - Randomest Item (Eureka)", false),
            new CheckLocation("Gustavson Gulch Storage Hut - Secret Item", false),
            new CheckLocation("Gustavson Gulch - Theatre Combat", false),
            new CheckLocation("Gustavson Gulch - Cafe Hut", false),
            new CheckLocation("Gustavson Gulch - Guard Barracks", false),
            new CheckLocation("Gustavson Gulch Treasure Cave - Bottom Chest (Item 1)", false),
            new CheckLocation("Gustavson Gulch Treasure Cave - Bottom Chest (Item 2)", false),
            new CheckLocation("Gustavson Gulch Treasure Cave - Middle Chest", false),
            new CheckLocation("Gustavson Gulch Destroyed - Dynamite Crate", false),
            new CheckLocation("Railroad Camp (East) - Rock Monster's Remains (Dr. Morton's Quest)", false),
            new CheckLocation("The Perfessor's House - Show the Stone Arrow", false),
            new CheckLocation("Kole Ridge Mine - First Locker (Item 1)", false),
            new CheckLocation("Kole Ridge Mine - First Locker (Item 2)", false),
            new CheckLocation("Kole Ridge Mine (Level 2) - Triangular Stones", false),
            new CheckLocation("Kole Ridge Mine (Level 2) - Bean-Iron Deposit", false),
            new CheckLocation("Kole Ridge Mine (Level 3) - Pick-Head", false),
            new CheckLocation("Butterfield Ranch - Rope on Fence", false),
            new CheckLocation("Butterfield Ranch - Fireplace", false),
            new CheckLocation("Butterfield Ranch Barn - Milk Shelf", false),
            new CheckLocation("Butterfield Ranch Barn - Toybox", false),
            new CheckLocation("Dynamite Dan's - Item 1", false),
            new CheckLocation("Snake Spring - Temporal Rift", false),
            new CheckLocation("Old Mission Catacombs - First Skull", false),
            new CheckLocation("Old Mission Catacombs - Third Skull", false),
            new CheckLocation("Old Mission Catacombs - Cemented Skull Pile", false),
            new CheckLocation("Old Mission Catacombs - Trash Pile", false),
            new CheckLocation("Old Mission Catacombs - Saint Beefus Defeated (Item 1)", false),
            new CheckLocation("Old Mission Catacombs - Saint Beefus Defeated (Item 2)", false),
            new CheckLocation("Old Mission Catacombs - Santa Cortada Defeated (Item 1)", false),
            new CheckLocation("Old Mission Catacombs - Santa Cortada Defeated (Item 2)", false),
            new CheckLocation("Old Mission Catacombs - Saint Pope Defeated (Item 1)", false),
            new CheckLocation("Old Mission Catacombs - Saint Pope Defeated (Item 2)", false),
            new CheckLocation("Old Mission - Holy Relic Quest Completed", false),
            new CheckLocation("Destroyed Campsite - Knapsack", false),
            new CheckLocation("Clown Campsite - Clowns Killed (Item 1)", false),
            new CheckLocation("Clown Campsite - Clowns Killed (Item 2)", false),
            new CheckLocation("Old Millinery - Office Safe", false),
            new CheckLocation("Rescue Mission - Shop Item 1", false),
            new CheckLocation("Rescue Mission - Shop Item 2", false),
            new CheckLocation("The Silver Plater - Plated the Turnip", false),
            new CheckLocation("The Silver Plater - Plated Barbed Wire", false),
            new CheckLocation("Lost Dutch Oven Mine - Sluice", false),
            new CheckLocation("Lost Dutch Oven Mine (Level 1) - Lockers (Item 1)", false),
            new CheckLocation("Lost Dutch Oven Mine (Level 1) - Lockers (Item 2)", false),
            new CheckLocation("Lost Dutch Oven Mine (Level 1) - Spittoon", false),
            new CheckLocation("Lost Dutch Oven Mine (Pit) - Emerald Rock", false),
            new CheckLocation("El Vibrato Chamber (Lost Dutch Oven Mine) - Leftmost Box", false),
            new CheckLocation("El Vibrato Chamber (Lost Dutch Oven Mine) - Locked Box", false),
            new CheckLocation("El Vibrato Ruin - Cylinder", false),
            new CheckLocation("Fort Alldead - Trash Can", false),
            new CheckLocation("Fort Alldead - Mass Grave Item", false),
            new CheckLocation("Fort Alldead - Knapsack (Item 1)", false),
            new CheckLocation("Fort Alldead - Knapsack (Item 2)", false),
            new CheckLocation("Fort Alldead Privy - Bottom-Right Corner", false),
            new CheckLocation("Fort Alldead Privy - Broken Toilet", false),
            new CheckLocation("Fort Alldead Barracks - Bottom-Right Footlocker", false),
            new CheckLocation("Lazy-A Dude Ranch - Purchased Herbal Remedy", false),
            new CheckLocation("Lazy-A Dude Ranch - Dreads Dude Hat Trade", false),
            new CheckLocation("Lazy-A Dude Ranch - Cowsbane Harvest", false),
            new CheckLocation("Abandoned Pickle Factory Cukes Room - Ghost Put To Rest (Item 2)", false),
            new CheckLocation("Abandoned Pickle Factory Salt Room - Ghost Put To Rest (Item 2)", false),
            new CheckLocation("Abandoned Pickle Factory Vinegar Room - Ghost Put To Rest (Item 2)", false),
            new CheckLocation("Abandoned Pickle Factory Vinegar Room - Coal Cart", false),
            new CheckLocation("Abandoned Pickle Factory - Puzzle Solved", false),
            new CheckLocation("Humming Cave - Grass Outside", false),
            new CheckLocation("Humming Cave - Bean-Iron Deposit", false),
            new CheckLocation("Bizarre Ruin - Half-Buried Pedestal", false),
            new CheckLocation("Circus - Ticket Booth", false),
            new CheckLocation("Circus - Test Your ____ (Ticket Prize)", false),
            new CheckLocation("Circus - Test Your Might (Large Prize)", false),
            new CheckLocation("Circus - Test Your Might (Small Prize)", false),
            new CheckLocation("Circus - Test Your Mind (Large Prize)", false),
            new CheckLocation("Circus - Test Your Mind (Small Prize)", false),
            new CheckLocation("Circus - Test Your Aim (Large Prize)", false),
            new CheckLocation("Circus - Test Your Aim (Small Prize)", false),
            new CheckLocation("Circus - Balloon Vendor", false),
            new CheckLocation("Circus Lost & Found - Item 1", false),
            new CheckLocation("Circus Lost & Found - Item 2", false),
            new CheckLocation("Circus Lost & Found - Item 3", false),
            new CheckLocation("Circus Lost & Found - Item 4", false),
            new CheckLocation("Circus - Slide Whistle Reward", false),
            new CheckLocation("Circus Kid - Lucky Cap Trade", false),
            new CheckLocation("Circus - Survived the Main Act", false),
            new CheckLocation("Circus - Barnaby Bob's Safe", false),
            new CheckLocation("Breadwood Mayor's Office - Soup Quest Accepted", false),
            new CheckLocation("Breadwood - Spittoon", false),
            new CheckLocation("Breadwood Trading Post - Item 1", false),
            new CheckLocation("Breadwood Trading Post - Item 2", false),
            new CheckLocation("Breadwood Trading Post - Item 3", false),
            new CheckLocation("Breadwood Trading Post - Item 4", false),
            new CheckLocation("Breadwood Trading Post - Item 5", false),
            new CheckLocation("Breadwood Trading Post - Item 6", false),
            new CheckLocation("Breadwood Trading Post - Item 7", false),
            new CheckLocation("Breadwood Trading Post - Item 8", false),
            new CheckLocation("Breadwood Trading Post - Item 9", false),
            new CheckLocation("Breadwood Trading Post - Item 10", false),
            new CheckLocation("Breadwood Bunkhouse - Hobart's Camera", false),
            new CheckLocation("Breadwood Bunkhouse - Footlocker", false),
            new CheckLocation("Ghostwood Town Hall - Issued Permit", false),
            new CheckLocation("Ghostwood - Ghost Cactus", false),
            new CheckLocation("Ghostwood - Sharpened Pencil", false),
            new CheckLocation("Ghostwood Town Hall - Issued ID", false),
            new CheckLocation("Ghostwood Office Supply - Stapler", false),
            new CheckLocation("Ghostwood Jail - Stapled Report", false),
            new CheckLocation("Ghostwood Stable - Got IDDTF", false),
            new CheckLocation("Ghostwood Salooooon - Staple Remover", false),
            new CheckLocation("Ghostwood Town Hall - The Final Form", false),
            new CheckLocation("Ghostwood Town Hall - Permit Finally Processed", false),
            new CheckLocation("Ghostwood Salooooon - Whiskey Bottle", false),
            new CheckLocation("Postal Way Station - Top-Right Newspaper Stack", false),
            new CheckLocation("Postal Way Station - Middle Newspaper Stack", false),
            new CheckLocation("Chuck's House - Bedroom Dresser", false),
            new CheckLocation("Chuck's House Cellar - Mail Bag", false),
            new CheckLocation("Chuck's House Cellar - Bookcase (Item 1)", false),
            new CheckLocation("Chuck's House Cellar - Bookcase (Item 2)", false),
            new CheckLocation("Chuck's House Cellar - Bookcase (Item 3)", false),
            new CheckLocation("Chuck's House Cellar - Nightstand", false),
            new CheckLocation("Soupstock Lode (Level 1) - Workbench Toolbox (Item 1)", false),
            new CheckLocation("Soupstock Lode (Level 1) - Workbench Toolbox (Item 2)", false),
            new CheckLocation("Soupstock Lode (Level 1) - Bean-Iron Deposit (Bottom Left)", false),
            new CheckLocation("Soupstock Lode (Elevator Room) - Knapsack", false),
            new CheckLocation("El Vibrato Chamber (Soupstock Lode) - Chest", false),
            new CheckLocation("Ol' Schmaltz Brewery - Dead Guy", false),
            new CheckLocation("Ol' Schmaltz Brewery - Deceased Yeast Beast", false),
            new CheckLocation("Ol' Schmaltz Brewery - Shelf", false),
            new CheckLocation("Baker Boys' Hideout - Bread Recovered", false),
            new CheckLocation("Military Cemetery - Shovel By Coffins", false),
            new CheckLocation("Military Cemetery - Shed Tools", false),
            new CheckLocation("Military Cemetery - Plot 13", false),
            new CheckLocation("Military Cemetery - Plot 420", false),
            new CheckLocation("Military Cemetery - Plot 666", false),
            new CheckLocation("Military Cemetery - Puzzle Plots Solved", false),
            new CheckLocation("Military Cemetery - 2nd Lt., 69th Innuendo Div.", false),
            new CheckLocation("Fort Memoriam - Candy Shelf", false),
            new CheckLocation("Fort Memoriam Barracks - Bookshelf", false),
            new CheckLocation("Fort Memoriam Barracks - Trash Pile", false),
            new CheckLocation("Fort Memoriam Barracks - Spittoon", false),
            new CheckLocation("Fort Memoriam - All Battles Cleared", false),
            new CheckLocation("Alexandria Ranch - Ruined Bookshelf (Left)", false),
            new CheckLocation("Alexandria Ranch - Smoldering Book Pile", false),
            new CheckLocation("Alexandria Ranch - Ruined Bookshelf (Right)", false),
            new CheckLocation("Alexandria Ranch Vault - Right Bookshelf", false),
            new CheckLocation("Alexandria Ranch Vault - Middle Bookshelf", false),
            new CheckLocation("Alexandria Ranch Vault - Left Bookshelf", false),
            new CheckLocation("Alexandria Ranch Vault - Glass Case (Right)", false),
            new CheckLocation("Alexandria Ranch Vault - Glass Case (Middle)", false),
            new CheckLocation("Alexandria Ranch Vault - Glass Case (Left)", false),
            new CheckLocation("Curly's Cairn - Under the Cairn", false),
            new CheckLocation("Roy Bean's House - Spittoon", false),
            new CheckLocation("Roy Bean's House - Honey Bean", false),
            new CheckLocation("Jelly Bean Thieves' Hideout - Thieves Killed (Item 1)", false),
            new CheckLocation("Jelly Bean Thieves' Hideout - Thieves Killed (Item 2)", false),
            new CheckLocation("Jelly Bean Thieves' Hideout - Crate Beside Stove", false),
            new CheckLocation("Jelly Bean Thieves' Hideout - Crate Beside Bed", false),
            new CheckLocation("Jelly Bean Thieves' Hideout - Jellybean Jar", false),
            new CheckLocation("Ol' Granddad (Floor 4) - Jellybean Jar", false),
            new CheckLocation("Shroomcave - First Magic Mushroom", false),
            new CheckLocation("Shroomcave - Second Magic Mushroom", false),
            new CheckLocation("Shroomcave - Third Magic Mushroom", false),
            new CheckLocation("Shroomcave - Dirty Knapsack", false),
            new CheckLocation("Shroomcave - Sleeping Necromancer (Item 1)", false),
            new CheckLocation("Shroomcave - Sleeping Necromancer (Item 2)", false),
            new CheckLocation("Shroomcave (Hidden Lounge) - Lava Lamp", false),
            new CheckLocation("Shroomcave (Hidden Lounge) - Jellybean Jar", false),
            new CheckLocation("Fort of Darkness (First Tent) - Irene's Pliers", false),
            new CheckLocation("Fort of Darkness (First Tent) - Free Mushroom", false),
            new CheckLocation("Fort of Darkness (Second Tent) - Animal Skeleton", false),
            new CheckLocation("Fort of Darkness (Second Tent) - Bone Trader (Chips)", false),
            new CheckLocation("Fort of Darkness (Second Tent) - Bone Trader (Bones)", false),
            new CheckLocation("Fort of Darkness (Second Tent) - Bone Trader (10 Gold Teeth)", false),
            new CheckLocation("Fort of Darkness (Second Tent) - Bone Trader (23 Gold Teeth)", false),
            new CheckLocation("Fort of Darkness (Fifth Tent) - Gun Safe", false),
            new CheckLocation("Fort of Darkness (Fifth Tent) - Bookcase", false),
            new CheckLocation("Fort of Darkness - Temporal Rift", false),
            new CheckLocation("Fort Treason Barracks - Top-Left Footlocker", false),
            new CheckLocation("Fort Treason Barracks - Top-Right Footlocker (Item 1)", false),
            new CheckLocation("Fort Treason Barracks - Top-Right Footlocker (Item 2)", false),
            new CheckLocation("Fort Treason Barracks - Bottom-Right Footlocker", false),
            new CheckLocation("Jumbleneck Mine - Rock Pile By Elevator", false),
            new CheckLocation("Jumbleneck Mine - Grease Barrel", false),
            new CheckLocation("Jumbleneck Mine Foreman's Office - Hatrack", false),
            new CheckLocation("Jumbleneck Mine Foreman's Office - Desk", false),
            new CheckLocation("Jumbleneck Mine Foreman's Office - Safe (Item 1)", false),
            new CheckLocation("Jumbleneck Mine Foreman's Office - Safe (Item 2)", false),
            new CheckLocation("Jumbleneck Mine (Inside) - The Pick in the Stone", false),
            new CheckLocation("Jumbleneck Mine (Left Tunnel) - Lunchbox", false),
            new CheckLocation("Jumbleneck Mine (Left Tunnel) - Bean-Iron Deposit", false),
            new CheckLocation("Jumbleneck Mine (Left Tunnel) - Dynamite Crate", false),
            new CheckLocation("Jumbleneck Mine (Right Tunnel) - Idol", false),
            new CheckLocation("El Vibrato Construction Facility - BUGAANZEVE", false),
            new CheckLocation("Curious Abandoned Well Facility (Equipment Fabrication) - Item 1", false),
            new CheckLocation("Curious Abandoned Well Facility (Equipment Fabrication) - Item 2", false),
            new CheckLocation("Curious Abandoned Well Facility (Secondary Storage) - Top Chest", false),
            new CheckLocation("Curious Abandoned Well Facility (Secondary Storage) - Bottom Chest", false),
            new CheckLocation("Curious Abandoned Well Facility (Secondary Storage) - Weird Device", false),
            new CheckLocation("Reboot Hill (Plot 1) - Granddaughter Puzzle", false),
            new CheckLocation("Reboot Hill (Plot 1) - Wise Ol' Jed Marmot's Grave", false),
            new CheckLocation("Reboot Hill (Plot 1) - Big Bob Hurlingham's Grave", false),
            new CheckLocation("Reboot Hill (Plot 1) - Sweet Monument", false),
            new CheckLocation("Reboot Hill (Plot 2) - Dink 'Scotch' Terkinson's Grave", false),
            new CheckLocation("Reboot Hill (Plot 2) - Fred Deeks' Grave", false),
            new CheckLocation("Reboot Hill (Plot 2) - Annette Jangle's Grave", false),
            new CheckLocation("Reboot Hill (Plot 2) - Picnic", false),
            new CheckLocation("Reboot Hill (Plot 2) - Fancy Tomb (Left)", false),
            new CheckLocation("Reboot Hill (Plot 2) - Fancy Tomb (Middle)", false),
            new CheckLocation("Reboot Hill (Plot 2) - Fancy Tomb (Right)", false),
            new CheckLocation("Reboot Hill (Plot 3) - Paulette Tootsbury's Grave", false),
            new CheckLocation("Reboot Hill (Plot 3) - Cultists' Pedestal", false),
            new CheckLocation("Reboot Hill (Plot 3) - Outhouse", false),
            new CheckLocation("Reboot Hill (Plot 3) - Stanrietta Minkleston's Grave", false),
            new CheckLocation("Reboot Hill (Plot 3) - Bernard's Reward", false),
            new CheckLocation("ReBoot Hill - Tontine Treasure Chest", false),
            new CheckLocation("The West Pole - Petroglyph Puzzle Solved", false),
            new CheckLocation("The West Pole - Leftmost Cairn (Dr. Morton's Quest)", false),
            new CheckLocation("Temporal Nexus - Camaro", false),
            new CheckLocation("Temporal Nexus - Stagecoach", false),
            new CheckLocation("Temporal Nexus - Robot", false),
            new CheckLocation("Temporal Nexus - Jawbone", false),
            new CheckLocation("The Great Garbanzo's Hideout - Between the Cushions", false),
            new CheckLocation("The Great Garbanzo's Hideout - Under the Pillow", false),
            new CheckLocation("The Great Garbanzo's Hideout - Bookcase", false),
            new CheckLocation("The Great Garbanzo's Hideout - Bean-Iron Deposit", false),
            new CheckLocation("The Old Medicine Show - Bookcase", false),
            new CheckLocation("The Old Medicine Show - Nighstand (Item 1)", false),
            new CheckLocation("The Old Medicine Show - Nighstand (Item 2)", false),
            new CheckLocation("The Old Medicine Show - Nighstand (Item 3)", false),
            new CheckLocation("Hellstrom Ranch (Barn) - Bookshelf", false),
            new CheckLocation("Petting Cemetery - Accepted Buffalo Quest", false),
            new CheckLocation("Buffalo Pile (Storage/Assembly) - Robe Next to Slab", false),
            new CheckLocation("Buffalo Pile (Bathroom) - Magazines", false),
            new CheckLocation("Buffalo Pile (Bathroom) - Trash Pile", false),
            new CheckLocation("Buffalo Pile (Sleeping Quarters) - Left Footlocker (Item 1)", false),
            new CheckLocation("Buffalo Pile (Sleeping Quarters) - Left Footlocker (Item 2)", false),
            new CheckLocation("Buffalo Pile (Sleeping Quarters) - Right Footlocker", false),
            new CheckLocation("Buffalo Pile (Sleeping Quarters) - Pedestal", false),
            new CheckLocation("Madness Maw Mine (Level 2) - Bean-Iron Deposit", false),
            new CheckLocation("Madness Maw Mine (Level 3) - Head Cultist", false),
            new CheckLocation("Madness Maw Mine (Curly's Cave) - Nightstand", false),
            new CheckLocation("Madness Maw Mine (Curly's Cave) - Pie Safe", false),
            new CheckLocation("Madness Maw Mine (Level 4) - Bean-Iron Deposit", false),
            new CheckLocation("El Vibrato Outpost (Madness Maw Mine) - Cylinder", false),
            new CheckLocation("El Vibrato Outpost (Madness Maw Mine) - Cards", false),
            new CheckLocation("El Vibrato Outpost (Madness Maw Mine) - Trash Pile", false),
            new CheckLocation("El Vibrato Outpost (Madness Maw Mine) - Vending Machine (SOMFUKRO)", false),
            new CheckLocation("El Vibrato Outpost (Madness Maw Mine) - Vending Machine (ZEVENOKKRO)", false),
            new CheckLocation("El Vibrato Outpost (Madness Maw Mine) - Vending Machine (BUKUZKRO)", false),
            new CheckLocation("Kellogg Ranch (Main Building) - Loose Floorboard", false),
            new CheckLocation("Kellogg Ranch (Office) - Animal Skeleton", false),
            new CheckLocation("Kellogg Ranch (Office) - Desk Drawer", false),
            new CheckLocation("Kellogg Ranch (Dormitory) - Top-Left Bed", false),
            new CheckLocation("Kellogg Ranch (Dormitory) - Bottom-Middle Bed", false),
            new CheckLocation("Kellogg Ranch (Dormitory) - First Locker (Item 1)", false),
            new CheckLocation("Kellogg Ranch (Dormitory) - First Locker (Item 2)", false),
            new CheckLocation("Kellogg Ranch (Dormitory) - Second Locker", false),
            new CheckLocation("Kellogg Ranch (Dormitory) - Fourth Locker", false),
            new CheckLocation("Kellogg Ranch (Dormitory) - Fifth Locker", false),
            new CheckLocation("Kellogg Ranch (Dormitory) - Sixth Locker (Item 1)", false),
            new CheckLocation("Kellogg Ranch (Dormitory) - Sixth Locker (Item 2)", false),
            new CheckLocation("Kellogg Ranch (Kitchen) - Dough Baked", false),
            new CheckLocation("Kellogg Ranch (Barn) - Barbed Wire", false),
            new CheckLocation("Kellogg Ranch (Barn) - Grain Pile", false),
            new CheckLocation("Necromancer's Tower - Necromancer Defeated", false),
            new CheckLocation("Frisco - Flier on the Street", false),
            new CheckLocation("Frisco - Spittoon", false),
            new CheckLocation("Fort Unnecessary - Administration Desk", false),
            new CheckLocation("Fort Unnecessary - Time Portal", false),
            new CheckLocation("Abandoned Mine - Drywasher", false),
            new CheckLocation("Abandoned Mine - Rocks to Right of Entrance", false),
            new CheckLocation("Abandoned Mine (Inside) - Bean-Iron Deposit", false),
            new CheckLocation("Abandoned Mine (Side Tunnel 1) - Bean-Iron Deposit", false),
            new CheckLocation("Abandoned Mine (Side Tunnel 2) - Bean-Iron Deposit", false),
            new CheckLocation("Abandoned Mine (Side Tunnel 2) - Drilling Machine", false),
            new CheckLocation("El Vibrato Storage Room - Card Table (Item 1)", false),
            new CheckLocation("El Vibrato Storage Room - Card Table (Item 2)", false),
            new CheckLocation("El Vibrato Storage Room - Cylinder", false),
            new CheckLocation("Dr. Morton's House - Workbench", false),
            new CheckLocation("Morton's Quarry (Tiny Diverticulum) - Hex Puzzle", false),
            new CheckLocation("Morton's Quarry - Dr. Morton's Quest Completion", false),
            new CheckLocation("Old Cave - Weird Rock", false),
            new CheckLocation("Jeweler's Cabin - Coal", false),
            new CheckLocation("Jeweler's Cabin - Sapphire", false),
            new CheckLocation("Jeweler's Cabin - Cowseye", false),
            new CheckLocation("Jeweler's Cabin - Diamond", false),
            new CheckLocation("Jeweler's Cabin - Emerald", false),
            new CheckLocation("Jeweler's Cabin - Ruby", false),
            new CheckLocation("Jeweler's Cabin - Silicon", false),
            new CheckLocation("Jeweler's Cabin - Diorite", false),
            new CheckLocation("Jeweler's Cabin - Spectacles", false),
            new CheckLocation("El Vibrato Chamber (Curious False Mountain) - Chronokey Fabrication", false),
            new CheckLocation("Alamo Rent-A-Mule - Rented a Mule", false),
            new CheckLocation("Curious Flat Plain - Explorer Skeleton", false),
            new CheckLocation("Curious Flat Plain - Garbage Return", false),
            new CheckLocation("Moonshine Still - Free Jar", false),
            new CheckLocation("Deepest Delve Mine - Coal Smasher 5000", false),
            new CheckLocation("Deepest Delve Mine (Alt Entrance) - Toolbox", false),
            new CheckLocation("Deepest Delve Mine (Alt Entrance) - Bean-Iron Deposit", false),
            new CheckLocation("Deepest Delve Mine (Level 2) - Cult Altar", false),
            new CheckLocation("Deepest Delve Mine (Level 2) - Bracelet", false),
            new CheckLocation("El Vibrato Control Center - El Vibrato Quest Completion", false),
            new CheckLocation("Halloway's Hideaway - Shop Item 1", false),
            new CheckLocation("Halloway's Hideaway - Shop Item 2", false),
            new CheckLocation("Halloway's Hideaway - Half of Curly's Map", false),
            new CheckLocation("Halloway's Hideaway - X Marks the Spot", false),
            new CheckLocation("Back of Gun Manor - Coal Man Skeleton", true),
            new CheckLocation("Back of Gun Manor - Compost Heap", true),
            new CheckLocation("Gun Manor Hedge Maze - Bean Bush", true),
            new CheckLocation("Gun Manor Hedge Maze - Hedge Wizard Defeated (Item 1)", true),
            new CheckLocation("Gun Manor Hedge Maze - Hedge Wizard Defeated (Item 2)", true),
            new CheckLocation("Gun Manor Hedge Maze - Hedge Wizard's Chest", true),
            new CheckLocation("Gun Manor Carriage House - Cabinet (Item 1)", true),
            new CheckLocation("Gun Manor Carriage House - Cabinet (Item 2)", true),
            new CheckLocation("Gun Manor Carriage House - Hedge Clippers", true),
            new CheckLocation("Gun Manor Carriage House - Leftmost Coach", true),
            new CheckLocation("Gun Manor Carriage House - Middle Coach", true),
            new CheckLocation("Gun Manor Carriage House - Lathe", true),
            new CheckLocation("Gun Manor Visitor Center - Token Smasher (Pistol)", true),
            new CheckLocation("Gun Manor Visitor Center - Token Smasher (Rifle)", true),
            new CheckLocation("Gun Manor Visitor Center - Token Smasher (Shotgun)", true),
            new CheckLocation("Gun Manor Visitor Center - Photo", true),
            new CheckLocation("Gun Manor Visitor Center - SouvenIRS Stand", true),
            new CheckLocation("Gun Manor Cellar - Rightmost Cocoon", true),
            new CheckLocation("Gun Manor Cellar - Box of Photos", true),
            new CheckLocation("Gun Manor Cellar - Pie Safe", true),
            new CheckLocation("Gun Manor Laboratory - Science Bench", true),
            new CheckLocation("Gun Manor Laboratory - Science Box", true),
            new CheckLocation("Gun Manor Laboratory - Workbench", true),
            new CheckLocation("Gun Manor Laboratory - Gunsmithing Tools (Worst Gun)", true),
            new CheckLocation("Gun Manor Laboratory - Gunsmithing Tools (Opus)", true),
            new CheckLocation("Gun Manor Parlor - Tea Cart", true),
            new CheckLocation("Gun Manor Parlor - Sofa Cushions (Murdered Chili)", true),
            new CheckLocation("Gun Manor Kitchen - Spice Rack", true),
            new CheckLocation("Gun Manor Kitchen - Cooked the Chili", true),
            new CheckLocation("Gun Manor Kitchen - Pot Shelf", true),
            new CheckLocation("Gun Manor Larder - Middle Shelf", true),
            new CheckLocation("Gun Manor Larder - Right Shelf", true),
            new CheckLocation("Gun Manor Pantry - Back Row, Third Rack", true),
            new CheckLocation("Gun Manor Dining Room - Dessert Cart", true),
            new CheckLocation("Gun Manor Library - Dictionary (\"Key\")", true),
            new CheckLocation("Gun Manor Library - Dictionary (\"Poach\")", true),
            new CheckLocation("Gun Manor Library - Fun Law Returned", true),
            new CheckLocation("Gun Manor Library - Duelling Banjos Returned", true),
            new CheckLocation("Gun Manor Library - Cipher Puzzle Solved", true),
            new CheckLocation("Gun Manor Art Gallery - Clock Noon Objection", true),
            new CheckLocation("Gun Manor Art Gallery - Lawyer Quest Completion", true),
            new CheckLocation("Gun Manor Restroom - Medicine Cabinet", true),
            new CheckLocation("Gun Manor Restroom - Shower", true),
            new CheckLocation("Gun Manor Guest Room 1 - Bookcase", true),
            new CheckLocation("Gun Manor Guest Room 3 - Sewing Basket", true),
            new CheckLocation("Gun Manor Guest Room 4 - Science Box", true),
            new CheckLocation("Gun Manor Manliness Room - Humidor", true),
            new CheckLocation("Gun Manor Manliness Room - Booze Cart", true),
            new CheckLocation("Mr. Gun's Bowling Room - Combat Drop 1", true),
            new CheckLocation("Mr. Gun's Bowling Room - Combat Drop 2", true),
            new CheckLocation("Mr. Gun's Bowling Room - Combat Drop 3", true),
            new CheckLocation("Mr. Gun's Bowling Room - Combat Drop 4", true),
            new CheckLocation("Gun Manor Trophy Room - Moose Head", true),
            new CheckLocation("Gun Manor Billiards Room - Cue Rack", true),
            new CheckLocation("Gun Manor Billiards Room - Pool Table", true),
            new CheckLocation("Gun Manor Music Room - Book Pile", true),
            new CheckLocation("Gun Manor Music Room - Piano", true),
            new CheckLocation("Gun Manor Children's Quarters - Chalkboard", true),
            new CheckLocation("Gun Manor Children's Quarters - Dollmine", true),
            new CheckLocation("Gun Manor Nursery - Crib", true),
            new CheckLocation("Gun Manor Nursery - Teddy Bear Guts", true),
            new CheckLocation("Gun Manor Toddler's Room - Toybox", true),
            new CheckLocation("Gun Manor Tween Room - Desk", true),
            new CheckLocation("Gun Manor Tween Room - Science Box", true),
            new CheckLocation("Gun Manor Tween Room - Wardrobe", true),
            new CheckLocation("Gun Manor Tween Room - Under the Bed", true),
            new CheckLocation("Mrs. Gun's Room - Display Case", true),
            new CheckLocation("Mrs. Gun's Room - All Ghosts Settled Peacefully", true),
            new CheckLocation("Gun Manor Belfry - Science Box", true),
            new CheckLocation("Wanderin' Sally's Camp - Item 1", false),
            new CheckLocation("Wanderin' Sally's Camp - Item 2", false),
            new CheckLocation("Wanderin' Sally's Camp - Item 3", false),
            new CheckLocation("Wanderin' Sally's Camp - Item 4", false),
            new CheckLocation("Wanderin' Sally's Camp - Item 5", false),
            new CheckLocation("Wanderin' Sally's Camp - Item 6", false),
            new CheckLocation("Wanderin' Sally's Camp - Item 7", false),
            new CheckLocation("Wanderin' Sally's Camp - Item 8", false),
            new CheckLocation("Wanderin' Sally's Camp - Item 9", false),
            new CheckLocation("Wanderin' Sally's Camp - Item 10", false),
            new CheckLocation("Wanderin' Sally's Camp - Item 11", false),
            new CheckLocation("Wanderin' Sally's Camp - Item 12", false),
            new CheckLocation("Wanderin' Sally's Camp - Item 13", false),
            new CheckLocation("Wanderin' Sally's Camp - Item 14", false),
            new CheckLocation("Random Encounter (Any Region) - 7th Encounter", false),
            new CheckLocation("Random Encounter (Any Region) - 13th Encounter", false),
            new CheckLocation("Random Encounter (Any Region) - 21st Encounter", false),
            new CheckLocation("Random Encounter (Region A) - Murder Pepper", false),
            new CheckLocation("Random Encounter (Region A) - Abandoned Stagecoach", false),
            new CheckLocation("Random Encounter (Region A) - Corpse of a Cowboy", false),
            new CheckLocation("Random Encounter (Region A) - Sharpshootin' Bandits", false),
            new CheckLocation("Random Encounter (Region A) - Moxious Goblin", false),
            new CheckLocation("Random Encounter (Region A) - Skeleton of a Beanslinger", false),
            new CheckLocation("Random Encounter (Region B) - Quilty-Pantsed Bandit", false),
            new CheckLocation("Random Encounter (Region B) - Scientifically-Minded Bandit", false),
            new CheckLocation("Random Encounter (Region B) - Hightailin' Bandit", false),
            new CheckLocation("Random Encounter (Region B) - Gulch Goblin Cactusjack", false),
            new CheckLocation("Random Encounter (Region B) - Gulch Goblin Flapjackjack", false),
            new CheckLocation("Random Encounter (Region B) - Gulch Goblin Crackerjack", false),
            new CheckLocation("Random Encounter (Region B) - Old Viking Skeleton", false),
            new CheckLocation("Random Encounter (Region B) - Old Wizard Skeleton (Item 1 - Beans)", false),
            new CheckLocation("Random Encounter (Region B) - Old Wizard Skeleton (Item 2 - Hat)", false),
            new CheckLocation("Random Encounter (Region B) - Cattle Baron's Skeleton (Item 1", false),
            new CheckLocation("Random Encounter (Region B) - Cattle Baron's Skeleton (Item 2)", false),
            new CheckLocation("Random Encounter (Region C) - Grizzled Skinner (Item 1)", false),
            new CheckLocation("Random Encounter (Region C) - Grizzled Skinner (Item 2)", false),
            new CheckLocation("Random Encounter (Region C) - Backwoods Butcher (Item 1)", false),
            new CheckLocation("Random Encounter (Region C) - Backwoods Butcher (Item 2)", false),
            new CheckLocation("Random Encounter (Region C) - Clown Hunter", false),
            new CheckLocation("Random Encounter (Region C) - Jackbooted Gulch Goblin", false),
            new CheckLocation("Random Encounter (Region C) - Gulch Goblin Juggler", false),
            new CheckLocation("Random Encounter (Region C) - Gulch Goblin Jeweler (Nail Ring)", false),
            new CheckLocation("Random Encounter (Region C) - Gulch Goblin Jeweler (Glass Ring)", false),
            new CheckLocation("Random Encounter (Region C) - Gulch Goblin Jeweler (Lead Ring)", false),
            new CheckLocation("Random Encounter (Region C) - Gulch Goblin Jeweler (Magic Ring)", false),
            new CheckLocation("Random Encounter (Region C) - Skeletal Cavalryman", false),
            new CheckLocation("Random Encounter (Region C) - Deformed Skeleton", false),
            new CheckLocation("Random Encounter (Region C) - Skeleton of an Old Hunter", false),
            new CheckLocation("Random Encounter (Region D) - 3rd Encounter", false),
            new CheckLocation("Random Encounter (Region D) - Big Tough Bandit", false),
            new CheckLocation("Random Encounter (Region D) - Strangely-Helmeted Lunatic", false),
            new CheckLocation("Random Encounter (Region D) - Breadwood Highwayman", false),
            new CheckLocation("Random Encounter (Region D) - Goblin Moon Weirdo", false),
            new CheckLocation("Random Encounter (Region D) - Goblin Chef", false),
            new CheckLocation("Random Encounter (Region D) - Foul-Mouthed Goblin", false),
            new CheckLocation("Random Encounter (Region D) - Shot-to-Hell Skeleton", false),
            new CheckLocation("Random Encounter (Region D) - Electrified Skeleton", false),
            new CheckLocation("Random Encounter (Region D) - Skeletal Rifleman", false),
            new CheckLocation("Random Encounter (Region D) - Drunk Ghost (Give Whiskey)", false),
            new CheckLocation("Random Encounter (Region E) - 13th Encounter", false),
            new CheckLocation("Random Encounter (Region E) - Vigilante Cultist Hunter", false),
            new CheckLocation("Random Encounter (Region E) - Wandering Necromancer Cultist (Hood)", false),
            new CheckLocation("Random Encounter (Region E) - Wandering Necromancer Cultist (Shovel)", false),
            new CheckLocation("Random Encounter (Region E) - Cow Hunter", false),
            new CheckLocation("Random Encounter (Region E) - Goblin Wearing a Buffalo Skull", false),
            new CheckLocation("Random Encounter (Region E) - Goblin Tuna Chef", false),
            new CheckLocation("Random Encounter (Region E) - Self-Deputized Goblin", false),
            new CheckLocation("Random Encounter (Region E) - Buffalo Soldier", false),
            new CheckLocation("Random Encounter (Region E) - Very Smart Skeleton", false),
            new CheckLocation("Random Encounter (Region E) - Buffalo Soldier Rifleman", false),
            new CheckLocation("Random Encounter (Region F) - Kurtz-Cult Runaway", false),
            new CheckLocation("Random Encounter (Region F) - Mad Hedge Chef", false),
            new CheckLocation("Random Encounter (Region F) - Cow-Cult Brigand", false),
            new CheckLocation("Random Encounter (Region F) - Cactus-Suited Goblin", false),
            new CheckLocation("Random Encounter (Region F) - Goblin Tanner", false),
            new CheckLocation("Random Encounter (Region F) - Goblin Grave Robber", false),
            new CheckLocation("Random Encounter (Region F) - Thick-Boned Skeleton (Boots)", false),
            new CheckLocation("Random Encounter (Region F) - Thick-Boned Skeleton (Brochure)", false),
            new CheckLocation("Random Encounter (Region F) - Mushroom-Covered Skeleton", false),
            new CheckLocation("Random Encounter (Region F) - Burnin' Skeleton", false),
            new CheckLocation("Random Encounter (Region G) - Insane Construction Worker", false),
            new CheckLocation("Random Encounter (Region G) - Burning Man", false),
            new CheckLocation("Random Encounter (Region G) - Bandit Jogger", false),
            new CheckLocation("Random Encounter (Region G) - Goblin Driftwood Sculptor (Weapon)", false),
            new CheckLocation("Random Encounter (Region G) - Goblin Driftwood Sculptor (Hat)", false),
            new CheckLocation("Random Encounter (Region G) - Goblin Driftwood Sculptor (Shield)", false),
            new CheckLocation("Random Encounter (Region G) - Goblin Clamdigger", false),
            new CheckLocation("Random Encounter (Region G) - Trigger-Happy Goblin Driftwood Sculptor", false),
            new CheckLocation("Random Encounter (Region G) - Conquistador's Skeleton", false),
            new CheckLocation("Random Encounter (Region G) - Seaweed-Draped Skeleton", false),
            new CheckLocation("Random Encounter (Region G) - Conquistador Dragoon Skeleton", false),
            new CheckLocation("Random Encounter (Region H) - Grizzled Mountain Man", false),
            new CheckLocation("Random Encounter (Region H) - Back-Country Chef-Magus", false),
            new CheckLocation("Random Encounter (Region H) - Barrista (Coffee)", false),
            new CheckLocation("Random Encounter (Region H) - Barrista (Pants)", false),
            new CheckLocation("Random Encounter (Region H) - Goblin Miner", false),
            new CheckLocation("Random Encounter (Region H) - Goblin Gunsmith", false),
            new CheckLocation("Random Encounter (Region H) - Flashy Goblin", false),
            new CheckLocation("Random Encounter (Region H) - Bigfoot Skeleton", false),
            new CheckLocation("Random Encounter (Region H) - Canada-Bound Skeleton", false),
            new CheckLocation("Random Encounter (Region H) - Skeletal Texas Ranger", false),
            new CheckLocation("Random Encounter (Region H) - Ghost Trapper", false),
            new CheckLocation("Rufus' Gifts - Gift 1", false),
            new CheckLocation("Rufus' Gifts - Gift 2", false),
            new CheckLocation("Rufus' Gifts - Gift 3", false),
            new CheckLocation("Rufus' Gifts - Gift 4", false),
            new CheckLocation("Rufus' Gifts - Gift 5", false),
            new CheckLocation("Opened Charred Locket", false),
            new CheckLocation("Magic-Infused Leaf Crafting - 3 Leaves", true),
            new CheckLocation("Magic-Infused Leaf Crafting - 5 Leaves", true),
            new CheckLocation("Magic-Infused Leaf Crafting - 7 Leaves", true),
            new CheckLocation("Spider Part Crafting - 4 Piles", true),
            new CheckLocation("Spider Part Crafting - 6 Piles", true),
            new CheckLocation("Spider Part Crafting - 8 Piles", true),
            new CheckLocation("Leatherworkery Crafting - Level 1 (Item 1)", false),
            new CheckLocation("Leatherworkery Crafting - Level 1 (Item 2)", false),
            new CheckLocation("Leatherworkery Crafting - Level 1 (Item 3)", false),
            new CheckLocation("Leatherworkery Crafting - Level 1 (Item 4)", false),
            new CheckLocation("Leatherworkery Crafting - Level 1 (Item 5)", false),
            new CheckLocation("Leatherworkery Crafting - Level 2 (Item 1)", false),
            new CheckLocation("Leatherworkery Crafting - Level 2 (Item 2)", false),
            new CheckLocation("Leatherworkery Crafting - Level 2 (Item 3)", false),
            new CheckLocation("Leatherworkery Crafting - Level 2 (Item 4)", false),
            new CheckLocation("Leatherworkery Crafting - Level 2 (Item 5)", false),
            new CheckLocation("Leatherworkery Crafting - Level 3 (Item 1)", false),
            new CheckLocation("Leatherworkery Crafting - Level 3 (Item 2)", false),
            new CheckLocation("Leatherworkery Crafting - Level 3 (Item 3)", false),
            new CheckLocation("Leatherworkery Crafting - Level 3 (Item 4)", false),
            new CheckLocation("Leatherworkery Crafting - Level 3 (Item 5)", false),
            new CheckLocation("Leatherworkery Crafting - Level 3 (Item 6)", false),
            new CheckLocation("Master Cookery Crafting - Level 1 (Item 1)", false),
            new CheckLocation("Master Cookery Crafting - Level 1 (Item 2)", false),
            new CheckLocation("Master Cookery Crafting - Level 1 (Item 3)", false),
            new CheckLocation("Master Cookery Crafting - Level 2 (Item 1)", false),
            new CheckLocation("Master Cookery Crafting - Level 2 (Item 2)", false),
            new CheckLocation("Master Cookery Crafting - Level 2 (Item 3)", false),
            new CheckLocation("Master Cookery Crafting - Level 3 (Item 1)", false),
            new CheckLocation("Master Cookery Crafting - Level 3 (Item 2)", false),
            new CheckLocation("Master Cookery Crafting - Level 3 (Item 3)", false),
            new CheckLocation("Progressive Loot - 3rd Grave Container", false),
            new CheckLocation("Progressive Loot - 6th Grave Container", false),
            new CheckLocation("Progressive Loot - 9th Grave Container", false),
            new CheckLocation("Progressive Loot - 12th Grave Container", false),
            new CheckLocation("Progressive Loot - 15th Grave Container", false),
            new CheckLocation("Progressive Loot - 18th Grave Container", false),
            new CheckLocation("Progressive Loot - 21st Grave Container", false),
            new CheckLocation("Progressive Loot - 24th Grave Container", false),
            new CheckLocation("Progressive Loot - 5th Army Container", false),
            new CheckLocation("Progressive Loot - 10th Army Container", false),
            new CheckLocation("Progressive Loot - 15th Army Container", false),
            new CheckLocation("Progressive Loot - 5th El Vibrato Container", false),
            new CheckLocation("Progressive Loot - 7th El Vibrato Container", false),
            new CheckLocation("Progressive Loot - 9th El Vibrato Container", false),
            new CheckLocation("Progressive Loot - 11th El Vibrato Container", false),
            new CheckLocation("Progressive Loot - 13th El Vibrato Container", false),
            new CheckLocation("Progressive Loot - 15th El Vibrato Container", false),
            new CheckLocation("Progressive Loot - 3rd Mining Container", false),
            new CheckLocation("Progressive Loot - 6th Mining Container", false),
            new CheckLocation("Progressive Loot - 9th Mining Container", false),
            new CheckLocation("Progressive Loot - 5th Ranch Container", false),
            new CheckLocation("Progressive Loot - 10th Ranch Container", false),
            new CheckLocation("Progressive Loot - 15th Ranch Container", false),
            new CheckLocation("Progressive Loot - 3rd Medical Container", false),
            new CheckLocation("Progressive Loot - 6th Medical Container", false),
            new CheckLocation("Progressive Loot - 9th Medical Container", false)
        };
    }
}
